#include <bits/stdc++.h>
#include <iostream>
#include <cctype>
using namespace std;

// cho n string va q truy vấn
// tìm các số string đã cho k co q truy vấn

bool truy(char x,string s) {
    for (int i = 0; i < s.size(); ++i) if (s[i] == x)  return true;
    return false;
}
long long slove(string a[10000],s) 
int main()
{
  ios_base::sync_with_stdio(false);cin.tie(0);cout.tie(0);
  // long long n,q ; cin >> n >> q;
  cin.ignore(); string a[n];
  char b[q],kq[q];
  for (int i = 0; i < n; ++i)  getline(cin,a[i]); 
  for (int i = 0; i < q; ++i)  cin >> b[i]; 
  for (int i = 0; i < n; ++i)
  { 
      if (truy(b[i],a[i])) F[]; 
  }
  return 0;
}